// src/views/tiled-carousel/horizontal/horizontal-simple-demo.vue
<script setup lang="ts">
import HorizontalTiledCarousel from '../../../components/tiled-carousel/horizontal.vue';

const cardData = [
  { title: "卡片 1", color: "#ff6b6b" },
  { title: "卡片 2", color: "#4ecdc4" },
  { title: "卡片 3", color: "#45b7d1" },
  { title: "卡片 4", color: "#96ceb4" },
  { title: "卡片 5", color: "#ffeaa7" },
];
</script>

<template>
  <div class="demo-wrapper">
    <HorizontalTiledCarousel :itemWidth="60" :gap="15" :autoplay="true" :interval="2000" :showIndicator="true"
      :showArrows="true">
      <div v-for="(card, index) in cardData" :key="index" class="demo-card" :style="{ backgroundColor: card.color }">
        <div>{{ card.title }}</div>
      </div>
    </HorizontalTiledCarousel>
  </div>
</template>

<style scoped>
.demo-wrapper {
  background-color: #ededed;
}

.demo-card {
  height: 200px;
  display: flex;
  justify-content: center;
  align-items: center;
  color: #ffffff;
  cursor: pointer;
}
</style>

// src/views/tiled-carousel/horizontal/horizontal-simple-demo.tsx
import HorizontalTiledCarousel from "../../../components/tiled-carousel/horizontal";

const HorizontalSimpleDemo: React.FC = () => {
	const cardData = [
		{ title: "卡片 1", color: "#ff6b6b" },
		{ title: "卡片 2", color: "#4ecdc4" },
		{ title: "卡片 3", color: "#45b7d1" },
		{ title: "卡片 4", color: "#96ceb4" },
		{ title: "卡片 5", color: "#ffeaa7" },
	];

	return (
		<div style={{ backgroundColor: "#ededed" }}>
			<HorizontalTiledCarousel itemWidth={60} gap={15} autoplay={true} interval={2000} showIndicator={true}>
				{cardData.map((item) => (
					<div
						style={{
							height: "200px",
							background: item.color,
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							justifyContent: "center",
							color: "#fff",
							cursor: "pointer",
							transition: "transform 0.3s",
						}}>
						<div>{item.title}</div>
					</div>
				))}
			</HorizontalTiledCarousel>
		</div>
	);
};

export default HorizontalSimpleDemo;
