// src/components/infinite-scroll-list/index.tsx
import React, { useRef, useEffect } from "react";

interface SeamlessScrollProps {
	list: unknown[];
	visibleRows?: number;
	fill?: boolean;
	speed?: number;
	interval?: number;
	stopOnHover?: boolean;
	children: React.ReactNode;
}

const SeamlessScroll: React.FC<SeamlessScrollProps> = ({
	list,
	visibleRows = 3,
	fill = true,
	speed = 1,
	interval = 40,
	stopOnHover = true,
	children,
}) => {
	const wrapRef = useRef<HTMLDivElement>(null);
	const boxRef = useRef<HTMLDivElement>(null);
	const timerRef = useRef<number | null>(null);
	const rowHeightRef = useRef(0);
	const singleCycleHeightRef = useRef(0);

	useEffect(() => {
		const initScroll = async () => {
			const box = boxRef.current;
			const wrap = wrapRef.current;

			if (!box || !wrap) return;

			const originRows = Array.from(box.children) as HTMLElement[];

			await new Promise((resolve) => setTimeout(resolve, 0));

			const firstRow = originRows[0] as HTMLElement;
			if (!firstRow) return;

			const height = firstRow.getBoundingClientRect().height;
			rowHeightRef.current = height;

			const curLen = originRows.length;
			if (curLen === 0) return;

			if (!fill && curLen <= visibleRows) {
				wrap.style.height = `${height * visibleRows}px`;
				return;
			}

			const repeatTimes = Math.max(1, Math.ceil(visibleRows / curLen));

			for (let i = 0; i < repeatTimes - 1; i++) {
				originRows.forEach((row) => box.appendChild(row.cloneNode(true)));
			}

			const singleCycleCount = curLen * repeatTimes;
			const firstCycleRows = (Array.from(box.querySelectorAll(".box-row")) as HTMLElement[]).slice(0, singleCycleCount);

			firstCycleRows.forEach((row) => box.appendChild(row.cloneNode(true)));

			const cycleHeight = height * singleCycleCount;
			singleCycleHeightRef.current = cycleHeight;

			wrap.style.height = `${height * visibleRows}px`;

			startScroll();
		};

		initScroll();

		return () => {
			stopScroll();
		};
	}, [list, visibleRows, fill, speed, interval]);

	const startScroll = () => {
		if (timerRef.current) return;

		timerRef.current = window.setInterval(() => {
			const box = boxRef.current;
			if (!box) return;

			box.scrollTop += speed;

			if (singleCycleHeightRef.current > 0 && box.scrollTop >= singleCycleHeightRef.current) {
				box.scrollTop -= singleCycleHeightRef.current;
			}
		}, interval);
	};

	const stopScroll = () => {
		if (timerRef.current) {
			window.clearInterval(timerRef.current);
			timerRef.current = null;
		}
	};

	const handleMouseEnter = () => {
		if (stopOnHover) stopScroll();
	};

	const handleMouseLeave = () => {
		if (stopOnHover) startScroll();
	};

	return (
		<div
			ref={wrapRef}
			className="seamless-scroll"
			onMouseEnter={handleMouseEnter}
			onMouseLeave={handleMouseLeave}
			style={{
				overflow: "hidden",
				position: "relative",
			}}>
			<div
				ref={boxRef}
				className="box-wrap"
				style={
					{
						height: "100%",
						overflow: "hidden",
						scrollbarWidth: "none",
					} as React.CSSProperties
				}>
				{children}
			</div>
		</div>
	);
};

export default SeamlessScroll;

// src/components/infinite-scroll-list/index.vue
<template>
    <div ref="wrapRef" class="seamless-scroll" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave">
        <div ref="boxRef" class="box-wrap">
            <slot />
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'

type Props = {
    list: unknown[]
    visibleRows?: number
    fill?: boolean
    speed?: number
    interval?: number
    stopOnHover?: boolean
}

const props = withDefaults(defineProps<Props>(), {
    visibleRows: 3,
    fill: true,
    speed: 1,
    interval: 40,
    stopOnHover: true,
})

const wrapRef = ref<HTMLDivElement>()
const boxRef = ref<HTMLDivElement>()

let timer: number | null = null
let rowHeight = 0
let singleCycleHeight = 0

onMounted(async () => {
    await nextTick()
    const box = boxRef.value!
    const wrap = wrapRef.value!

    let originRows: HTMLElement[]
    originRows = Array.from(box.children) as HTMLElement[]

    if (originRows.length === 0) return

    const firstRow = originRows[0]
    rowHeight = firstRow.getBoundingClientRect().height

    const curLen = originRows.length

    if (!props.fill && curLen <= props.visibleRows) {
        wrap.style.height = `${rowHeight * props.visibleRows}px`
        return
    }

    const repeatTimes = Math.max(1, Math.ceil(props.visibleRows / curLen))
    for (let i = 0; i < repeatTimes - 1; i++) {
        originRows.forEach((row) => box.appendChild(row.cloneNode(true)))
    }

    const singleCycleCount = curLen * repeatTimes

    let firstCycleRows: HTMLElement[]
    firstCycleRows = (Array.from(box.children) as HTMLElement[]).slice(0, singleCycleCount)

    firstCycleRows.forEach((row) => box.appendChild(row.cloneNode(true)))

    singleCycleHeight = rowHeight * singleCycleCount

    wrap.style.height = `${rowHeight * props.visibleRows}px`

    startScroll()
})

onUnmounted(() => stopScroll())

function startScroll() {
    if (timer) return
    timer = window.setInterval(() => {
        const box = boxRef.value!

        box.scrollTop += props.speed

        if (singleCycleHeight > 0 && box.scrollTop >= singleCycleHeight) {
            box.scrollTop -= singleCycleHeight
        }
    }, props.interval)
}

function stopScroll() {
    if (timer) {
        window.clearInterval(timer)
    }
    timer = null
}

function handleMouseEnter() {
    if (props.stopOnHover) stopScroll()
}

function handleMouseLeave() {
    if (props.stopOnHover) startScroll()
}
</script>

<style scoped>
.seamless-scroll {
    overflow: hidden;
    position: relative;
}

.box-wrap {
    height: 100%;
    scrollbar-width: none;
    overflow: hidden;
}

.box-wrap::-webkit-scrollbar {
    display: none;
}
</style>
