// src/components/showcase-carousel/vertical.tsx
import React, { useEffect, useRef, useState, useMemo } from "react";

type Props = {
	itemHeight?: number | string;
	gap?: number;
	autoplay?: boolean;
	interval?: number;
	showArrows?: boolean;
	showIndicator?: boolean;
	indicatorPosition?: "left" | "right";
	arrowSize?: number | string;
	initialIndex?: number;
	children?: React.ReactNode;
	change?: (activeIndex: number) => void;
	click?: (activeIndex: number) => void;
};

type LayoutCache = {
	viewportHeight: number;
	itemHeightPx: number;
	topOffset: number;
};

const cloneOffset = 2;

const VerticalShowcaseCarousel: React.FC<Props> = ({
	itemHeight = 60,
	gap = 0,
	autoplay = false,
	interval = 3000,
	showArrows = true,
	showIndicator = true,
	indicatorPosition = "right",
	arrowSize = 45,
	initialIndex = 0,
	children,
	change,
	click,
}) => {
	const viewportRef = useRef<HTMLDivElement | null>(null);
	const trackRef = useRef<HTMLDivElement | null>(null);

	const [layoutCache, setLayoutCache] = useState<LayoutCache>({ viewportHeight: 0, itemHeightPx: 0, topOffset: 0 });
	const [originItems, setOriginItems] = useState<React.ReactNode[]>([]);

	const [curRealIndex, setCurRealIndex] = useState<number>(0);
	const [curVirtualIndex, setCurVirtualIndex] = useState<number>(cloneOffset);

	const [isTransitioning, setIsTransitioning] = useState<boolean>(false);

	const autoplayTimer = useRef<number | null>(null);
	const viewportResizeObserver = useRef<ResizeObserver | null>(null);

	const virtualItems = useMemo(() => {
		const items = originItems;
		if (items.length <= 1) return items;
		return [...items.slice(-2), ...items, ...items.slice(0, 2)];
	}, [originItems]);

	const itemStyle = () => {
		if (typeof itemHeight === "number") {
			const vh = layoutCache.viewportHeight;
			const h = vh ? `${(vh * itemHeight) / 100}px` : `${itemHeight}%`;

			return { height: h, width: "100%" } as React.CSSProperties;
		}

		return { height: itemHeight as string, width: "100%" } as React.CSSProperties;
	};

	const arrowStyle = () => {
		if (typeof arrowSize === "number") {
			const size = arrowSize;
			return {
				width: `${size}px`,
				height: `${size}px`,
			} as React.CSSProperties;
		}
		const size = arrowSize || "45px";
		return { width: size, height: size } as React.CSSProperties;
	};

	const trackStyle = () => {
		const { viewportHeight, itemHeightPx, topOffset } = layoutCache;
		if (!viewportHeight || !itemHeightPx) {
			return {
				gap: `${gap}px`,
				transform: `translateY(0px)`,
				transition: isTransitioning ? "transform 0.4s ease-out" : "none",
			} as React.CSSProperties;
		}

		const translate = -(curVirtualIndex * (itemHeightPx + gap) + topOffset);
		return {
			gap: `${gap}px`,
			transform: `translateY(${translate}px)`,
			transition: isTransitioning ? "transform 0.4s ease-out" : "none",
		} as React.CSSProperties;
	};

	const indicatorStyle = useMemo(() => {
		const offset = "35px";
		if (indicatorPosition === "left") {
			return { left: offset, top: "50%", transform: "translateY(-50%)" } as React.CSSProperties;
		}
		return { right: offset, top: "50%", transform: "translateY(-50%)" } as React.CSSProperties;
	}, [indicatorPosition]);

	const realToVirtual = (realPos: number) => {
		const len = originItems.length || 0;
		if (len === 0) return cloneOffset;
		const normalized = ((realPos % len) + len) % len;
		return normalized + cloneOffset;
	};

	const virtualToReal = (virtualPos: number) => {
		const len = originItems.length || 0;
		if (len === 0) return 0;
		return (((virtualPos - cloneOffset) % len) + len) % len;
	};

	function initLayout() {
		setCurRealIndex(initialIndex || 0);
		setCurVirtualIndex(realToVirtual(initialIndex || 0));
	}

	function measureLayoutCache() {
		if (!viewportRef.current) return;

		const viewportHeight = viewportRef.current.clientHeight || 0;
		let itemHeightPx = 0;
		if (typeof itemHeight === "number") {
			itemHeightPx = (viewportHeight * itemHeight) / 100;
		}

		if (!itemHeightPx) {
			const firstChild = trackRef.current?.children[0] as HTMLElement | undefined;
			itemHeightPx = firstChild?.clientHeight || 0;
		}

		const topOffset = itemHeightPx / 2 - viewportHeight / 2;
		setLayoutCache({ viewportHeight, itemHeightPx, topOffset });
	}

	function moveToIndex(targetIndex: number, skipTransition = false) {
		const length = originItems.length;
		if (length === 0) return;

		if (skipTransition) {
			setIsTransitioning(false);
			setCurVirtualIndex((v) => {
				const newV = v + targetIndex;
				setCurRealIndex(virtualToReal(newV));
				return newV;
			});
			return;
		}

		setIsTransitioning(true);
		setCurVirtualIndex((v) => v + targetIndex);
	}

	const handlePrev = () => {
		clearAutoplay();
		moveToIndex(-1);
		setupAutoplay();
	};

	const handleNext = () => {
		clearAutoplay();
		moveToIndex(1);
		setupAutoplay();
	};

	const handleJumpTo = (realIdx: number) => {
		clearAutoplay();
		const virtualIndex = realToVirtual(realIdx);
		setIsTransitioning(true);
		setCurVirtualIndex(virtualIndex);
		setupAutoplay();
	};

	function handleTransitionEnd() {
		const len = originItems.length;
		if (len === 0) return;

		const virtualIndex = curVirtualIndex;
		if (virtualIndex < cloneOffset) {
			const newV = virtualIndex + len;
			moveToIndex(newV - virtualIndex, true);
			return;
		}

		if (virtualIndex >= cloneOffset + len) {
			const newV = virtualIndex - len;
			moveToIndex(newV - virtualIndex, true);
			return;
		}

		setCurRealIndex(virtualToReal(virtualIndex) % originItems.length);
	}

	function setupAutoplay() {
		if (!autoplay || originItems.length <= 1) return;
		clearAutoplay();
		autoplayTimer.current = window.setInterval(() => {
			moveToIndex(1);
		}, interval);
	}

	function clearAutoplay() {
		if (!autoplayTimer.current) return;
		clearInterval(autoplayTimer.current);
		autoplayTimer.current = null;
	}

	function onResize() {
		measureLayoutCache();
		setIsTransitioning(false);
	}

	function onClick(index: number) {
		const realIndex = virtualToReal(index);

		if (index > curVirtualIndex) {
			clearAutoplay();
			moveToIndex(1);
			setupAutoplay();
		}

		if (index < curVirtualIndex) {
			clearAutoplay();
			moveToIndex(-1);
			setupAutoplay();
		}

		if (typeof click === "function") {
			click(realIndex);
		}
	}

	useEffect(() => {
		const items = React.Children.toArray(children || []) as React.ReactNode[];
		setOriginItems(items.map((c) => c));

		const raf = window.requestAnimationFrame(() => {
			initLayout();
			measureLayoutCache();
			setupAutoplay();
		});

		window.addEventListener("resize", onResize);

		viewportResizeObserver.current = new ResizeObserver((entries) => {
			for (const entry of entries) {
				const height = entry.contentRect.height;
				if (height === layoutCache.viewportHeight) continue;
				measureLayoutCache();
				setIsTransitioning(false);
			}
		});
		if (viewportRef.current) {
			viewportResizeObserver.current.observe(viewportRef.current);
		}

		return () => {
			clearAutoplay();
			window.removeEventListener("resize", onResize);
			window.cancelAnimationFrame(raf);
			if (viewportResizeObserver.current) {
				viewportResizeObserver.current.disconnect();
				viewportResizeObserver.current = null;
			}
		};
	}, [children]);

	useEffect(() => {
		measureLayoutCache();
	}, [curVirtualIndex]);

	useEffect(() => {
		if (typeof change === "function") {
			change(curRealIndex);
		}
	}, [curRealIndex, change]);

	return (
		<div style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden" }}>
			{showArrows && originItems.length > 0 && (
				<div style={{ position: "absolute", inset: 0, zIndex: 10, pointerEvents: "none" }}>
					<button
						className="arrow prev"
						style={{
							...(arrowStyle() as React.CSSProperties),
							pointerEvents: "all",
							position: "absolute",
							left: "50%",
							transform: "translateX(-50%)",
							top: 12,
							border: "none",
							borderRadius: "50%",
							background: "rgba(0,0,0,0.25)",
							color: "#fff",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
						}}
						onClick={handlePrev}>
						<svg
							style={{ width: "60%", height: "60%", transform: "rotate(90deg)" }}
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth={2}>
							<polyline points="15 18 9 12 15 6" />
						</svg>
					</button>
					<button
						className="arrow next"
						style={{
							...(arrowStyle() as React.CSSProperties),
							pointerEvents: "all",
							position: "absolute",
							left: "50%",
							transform: "translateX(-50%)",
							bottom: 12,
							border: "none",
							borderRadius: "50%",
							background: "rgba(0,0,0,0.25)",
							color: "#fff",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
						}}
						onClick={handleNext}>
						<svg
							style={{ width: "60%", height: "60%", transform: "rotate(90deg)" }}
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth={2}>
							<polyline points="9 18 15 12 9 6" />
						</svg>
					</button>
				</div>
			)}

			<div
				ref={viewportRef}
				className="viewport"
				style={{ width: "100%", height: "100%", overflow: "hidden", position: "relative" }}>
				<div
					ref={trackRef}
					className="track"
					style={{
						display: "flex",
						flexDirection: "column",
						alignItems: "center",
						...(trackStyle() as React.CSSProperties),
					}}
					onTransitionEnd={handleTransitionEnd}>
					{virtualItems.map((child, idx) => (
						<div
							key={idx}
							style={{
								...(itemStyle() as React.CSSProperties),
								flexShrink: 0,
								display: "grid",
								alignItems: "stretch",
								justifyItems: "stretch",
							}}
							onClick={() => onClick(idx)}>
							{child}
						</div>
					))}
				</div>
			</div>

			{showIndicator && originItems.length > 0 && (
				<div
					className="indicator-bar"
					style={{
						height: "100%",
						position: "absolute",
						display: "flex",
						justifyContent: "center",
						flexDirection: "column",
						gap: 8,
						zIndex: 2,
						...(indicatorStyle as React.CSSProperties),
					}}>
					{originItems.map((_, idx) => (
						<span
							key={idx}
							className={`indicator ${idx === curRealIndex ? "active" : ""}`}
							onClick={() => handleJumpTo(idx)}
							style={{
								width: 4,
								height: "5%",
								background: idx === curRealIndex ? "#fff" : "rgba(255,255,255,0.45)",
								cursor: "pointer",
								transition: "all 0.25s",
							}}
						/>
					))}
				</div>
			)}
		</div>
	);
};

export default VerticalShowcaseCarousel;

// src/components/showcase-carousel/vertical.vue
<template>
    <div class="carousel-container">
        <div v-if="showArrows && originItems.length > 0" class="arrow-container">
            <button class="arrow prev" :style="arrowStyle" @click="handlePrev">
                <svg style="width:60%;height:60%;transform:rotate(90deg)" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2">
                    <polyline points="15 18 9 12 15 6"></polyline>
                </svg>
            </button>
            <button class="arrow next" :style="arrowStyle" @click="handleNext">
                <svg style="width:60%;height:60%;transform:rotate(90deg)" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2">
                    <polyline points="9 18 15 12 9 6"></polyline>
                </svg>
            </button>
        </div>

        <div ref="viewportRef" class="viewport">
            <div ref="trackRef" class="track" :style="trackStyle" @transitionend="handleTransitionEnd">
                <template v-for="(vnode, index) in virtualItems" :key="index">
                    <component :is="vnode" :style="itemStyle" @click="onClick(index)" />
                </template>
            </div>
        </div>

        <div v-if="showIndicator && originItems.length > 0" class="indicator-bar" :style="indicatorStyle">
            <span v-for="(_, idx) in originItems" :key="idx" class="indicator" :class="{ active: idx === curRealIndex }"
                @click="handleJumpTo(idx)" />
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, useSlots, nextTick, watch } from "vue";


const emit = defineEmits<{
    (e: 'change', activeIndex: number): void,
    (e: 'click', index: number): void;
}>();

type Props = {
    itemHeight?: number | string;
    gap?: number;
    autoplay?: boolean;
    interval?: number;
    showArrows?: boolean;
    showIndicator?: boolean;
    indicatorPosition?: 'left' | 'right';
    arrowSize?: number | string;
    initialIndex?: number;
}

const props = withDefaults(defineProps<Props>(), {
    itemHeight: 60,
    gap: 0,
    autoplay: false,
    interval: 3000,
    showArrows: true,
    showIndicator: true,
    indicatorPosition: 'right',
    arrowSize: 45,
    initialIndex: 0,
});

type LayoutCache = {
    viewportHeight: number;
    itemHeightPx: number;
    topOffset: number;
}

const layoutCache = ref<LayoutCache>({
    viewportHeight: 0,
    itemHeightPx: 0,
    topOffset: 0,
});

const slots = useSlots();

const viewportRef = ref<HTMLElement | null>(null);
const viewportResizeObserver = ref<ResizeObserver | null>(null);
const trackRef = ref<HTMLElement | null>(null);

const cloneOffset = 2;
const curRealIndex = ref<number>(0);
const curVirtualIndex = ref<number>(0);

const isTransitioning = ref<boolean>(false);
const autoplayTimerId = ref<number | null>(null);

const originItems = ref<any[]>([]);
const virtualItems = computed(() => {
    const items = originItems.value;
    if (items.length <= 1) return items;
    return [...items.slice(-2), ...items, ...items.slice(0, 2)];
});

const itemStyle = computed(() => {
    if (typeof props.itemHeight === "number") {
        const vh = layoutCache.value.viewportHeight;
        const itemHeight = vh ? `${(vh * props.itemHeight) / 100}px` : `${props.itemHeight}%`;
        return { height: itemHeight, width: '100%' };
    }

    return { height: props.itemHeight as string, width: '100%' };
});
const arrowStyle = computed(() => {
    if (typeof props.arrowSize === "number") {
        const size = props.arrowSize;
        return {
            width: `${size}px`,
            height: `${size}px`,
        }
    }

    const size = props.arrowSize || "45px";
    return {
        width: size,
        height: size,
    }

});
const indicatorStyle = computed(() => {
    const offset = '35px';
    if (props.indicatorPosition === 'left') {
        return { left: offset, top: '50%', transform: 'translateY(-50%)' };
    }
    return { right: offset, top: '50%', transform: 'translateY(-50%)' };
});
const trackStyle = computed(() => {
    const { viewportHeight, itemHeightPx, topOffset } = layoutCache.value;

    if (!viewportHeight || !itemHeightPx) {
        return {
            gap: `${props.gap}px`,
            transform: `translateY(0px)`,
            transition: isTransitioning.value ? "transform 0.4s ease-out" : "none",
        };
    }

    const translate = -(curVirtualIndex.value * (itemHeightPx + props.gap) + topOffset);
    return {
        gap: `${props.gap}px`,
        transform: `translateY(${translate}px)`,
        transition: isTransitioning.value ? "transform 0.4s ease-out" : "none",
    };
});

watch(curRealIndex, (value) => {
    emit('change', value);
}, { immediate: true });

onMounted(async () => {
    const slotTarget = slots.default ? slots.default() : [];
    originItems.value = (slotTarget[0]?.children || []) as any[];

    nextTick();

    initLayout();
    measureLayoutCache();

    setupAutoplay();
    window.addEventListener("resize", onResize);

    viewportResizeObserver.value = new ResizeObserver((entries) => {
        for (const entry of entries) {
            const height = entry.contentRect.height;
            if (height === layoutCache.value.viewportHeight) return;

            measureLayoutCache();
            isTransitioning.value = false;
        }
    });
    if (viewportRef.value) {
        viewportResizeObserver.value.observe(viewportRef.value);
    }
});

onUnmounted(() => {
    clearAutoplay();
    window.removeEventListener("resize", onResize);
    if (viewportResizeObserver.value) {
        viewportResizeObserver.value.disconnect();
        viewportResizeObserver.value = null;
    }
});

function initLayout() {
    curRealIndex.value = props.initialIndex || 0
    curVirtualIndex.value = realToVirtual(curRealIndex.value);
}

function measureLayoutCache() {
    if (!viewportRef.value) return;

    let viewportHeight = 0;
    let itemHeightPx = 0;
    let topOffset = 0;

    nextTick();

    viewportHeight = viewportRef.value.clientHeight;

    if (typeof props.itemHeight === "number") {
        itemHeightPx = (viewportHeight * props.itemHeight) / 100;
    }
    if (!itemHeightPx) {
        const firstChild = trackRef.value?.children[0] as HTMLElement | undefined;
        itemHeightPx = firstChild?.clientHeight || 0;
    }

    topOffset = itemHeightPx / 2 - viewportHeight / 2;

    layoutCache.value = { viewportHeight, itemHeightPx, topOffset };
}


function realToVirtual(realPos: number) {
    const len = originItems.value.length || 0;
    if (len === 0) return cloneOffset;

    const normalized = ((realPos % len) + len) % len;
    return normalized + cloneOffset;
}
function virtualToReal(virtualPos: number) {
    const len = originItems.value.length || 0;
    if (len === 0) return 0;

    return ((virtualPos - cloneOffset) % len + len) % len;
}

function moveToIndex(targetIndex: number, skipTransition = false) {
    const length = originItems.value.length;
    if (length === 0) return;

    //[ >2, 3, 1, 2, 3, 1, 2]
    //[ 1, >2, 3]
    if (skipTransition) {
        isTransitioning.value = false;

        //[ 2, >3, 1, 2, 3, 1, 2]
        curVirtualIndex.value = curVirtualIndex.value + targetIndex;
        //[ 1, 2, >3]
        curRealIndex.value = virtualToReal(curVirtualIndex.value);
        return
    }

    isTransitioning.value = true;
    curVirtualIndex.value = curVirtualIndex.value + targetIndex;
}

const handlePrev = () => {
    clearAutoplay();
    moveToIndex(-1);
    setupAutoplay();
};

const handleNext = () => {
    clearAutoplay();
    moveToIndex(1);
    setupAutoplay();
};

const handleJumpTo = (realIdx: number) => {
    clearAutoplay();
    const virtualIndex = realToVirtual(realIdx);
    isTransitioning.value = true;
    curVirtualIndex.value = virtualIndex;
    setupAutoplay();
};

function handleTransitionEnd() {
    const len = originItems.value.length;
    if (len === 0) return;

    const virtualIndex = curVirtualIndex.value;
    if (virtualIndex < cloneOffset) {
        const newV = virtualIndex + len;
        moveToIndex(newV - virtualIndex, true);
        return
    }

    if (virtualIndex >= cloneOffset + len) {
        const newV = virtualIndex - len;
        moveToIndex(newV - virtualIndex, true);
        return
    }
    curRealIndex.value = virtualToReal(virtualIndex) % originItems.value.length;
}

function setupAutoplay() {
    if (!props.autoplay || originItems.value.length <= 1) return;

    clearAutoplay();
    autoplayTimerId.value = window.setInterval(() => {
        moveToIndex(1);
    }, props.interval);
}
function clearAutoplay() {
    if (!autoplayTimerId.value) return;

    clearInterval(autoplayTimerId.value);
    autoplayTimerId.value = null;
}

function onResize() {
    measureLayoutCache();
    isTransitioning.value = false;
}

function onClick(index: number) {
    const realIndex = virtualToReal(index);

    if (index > curVirtualIndex.value) {
        clearAutoplay();
        moveToIndex(1);
        setupAutoplay();
    }

    if (index < curVirtualIndex.value) {
        clearAutoplay();
        moveToIndex(-1);
        setupAutoplay();
    }

    emit('click', realIndex);
}
</script>

<style scoped>
.carousel-container {
    position: relative;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.arrow-container {
    position: absolute;
    inset: 0;
    z-index: 10;
    pointer-events: none;
}

.arrow {
    pointer-events: all;
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    border: none;
    background: rgba(0, 0, 0, 0.25);
    color: #fff;
    cursor: pointer;
}

.arrow.prev {
    top: 12px;
}

.arrow.next {
    bottom: 12px;
}

.viewport {
    width: 100%;
    height: 100%;
    overflow: hidden;
    position: relative;
}

.track {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.track>* {
    flex-shrink: 0;
}

.indicator-bar {
    height: 100%;
    position: absolute;
    display: flex;
    justify-content: center;
    flex-direction: column;
    gap: 8px;
    z-index: 2;
}

.indicator {
    width: 4px;
    height: 5%;
    background: rgba(255, 255, 255, 0.45);
    cursor: pointer;
    transition: all 0.25s;
}

.indicator.active {
    background: #fff;
}
</style>
