// src/views/notice-carousel/vertical-demo.vue
<script setup lang="ts">
import { ref } from 'vue';
import NoticeCarousel from "../../components/notice-carousel/index.vue";

const messages = ref([
    '欢迎使用通知栏组件！',
    '新版本已发布，请及时更新',
    '限时优惠活动正在进行中',
    '重要通知：请查收最新邮件'
]);
</script>

<template>
    <div class="notice-demo">
        <NoticeCarousel :data="messages" direction="vertical" />
    </div>
</template>

<style scoped></style>

// src/views/notice-carousel/vertical-demo.tsx
import { useState } from "react";
import NoticeCarousel from "../../components/notice-carousel/index.tsx";

export default function NoticeVerticalDemo() {
	const [messages] = useState([
		"欢迎使用通知栏组件！",
		"新版本已发布，请及时更新",
		"限时优惠活动正在进行中",
		"重要通知：请查收最新邮件",
	]);

	return (
		<div className="notice-demo">
			<NoticeCarousel data={messages} direction="vertical" />
		</div>
	);
}
