// docs/example/infinite-scroll-list/vertical/vertical-simple-demo.tsx
import InfiniteVerticalScroll from "../../../../packages/components/src/infinite-scroll-list/vertical.tsx";

const InfiniteVerticalScrollDemo: React.FC = () => {
	const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`);

	return (
		<InfiniteVerticalScroll height={100}>
			{items.map((item, index) => (
				<div key={index}>
					<span>{item}</span>
				</div>
			))}
		</InfiniteVerticalScroll>
	);
};
export default InfiniteVerticalScrollDemo;

// docs/example/infinite-scroll-list/vertical/vertical-simple-demo.vue
<script setup lang="ts">
import InfiniteVerticalScroll from "../../../../packages/components/src/infinite-scroll-list/vertical.vue";

const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`)
</script>

<template>
    <InfiniteVerticalScroll :height="100">
        <div v-for="(item, idx) in items" :key="idx">
            {{ item }}
        </div>
    </InfiniteVerticalScroll>
</template>
