// src/views/infinite-scroll-list/horizontal/horizontal-simple-demo.tsx
import InfiniteHorizontalScroll from "../../../components/infinite-scroll-list/horizontal.tsx";

const InfiniteHorizontalScrollDemo: React.FC = () => {
	const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`);

	return (
		<InfiniteHorizontalScroll>
			{items.map((item, index) => (
				<div key={index} style={{ margin: "0 5px" }}>
					<span>{item}</span>
				</div>
			))}
		</InfiniteHorizontalScroll>
	);
};
export default InfiniteHorizontalScrollDemo;

// src/views/infinite-scroll-list/horizontal/horizontal-simple-demo.vue
<script setup lang="ts">
import InfiniteHorizontalScroll from "../../../components/infinite-scroll-list/horizontal.vue";

const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`)
</script>

<template>
    <InfiniteHorizontalScroll>
        <div v-for="(item, idx) in items" :key="idx" class="item-row">
            {{ item }}
        </div>
    </InfiniteHorizontalScroll>
</template>

<style>
.item-row {
    margin: 0 5px;
}
</style>
