// src/components/tiled-carousel/horizontal.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";

type Props = {
	itemWidth?: number | string;
	gap?: number;
	autoplay?: boolean;
	interval?: number;
	showArrows?: boolean;
	showIndicator?: boolean;
	arrowSize?: number | string;
	initialIndex?: number;
	children?: React.ReactNode;
};

type LayoutCache = {
	viewportWidth: number;
	itemWidthPx: number;
	leftOffset: number;
};

const cloneOffset = 2;

const HorizontalTiledCarousel: React.FC<Props> = ({
	itemWidth = 60,
	gap = 16,
	autoplay = false,
	interval = 3000,
	showArrows = true,
	showIndicator = true,
	arrowSize = 45,
	initialIndex = 0,
	children,
}) => {
	const viewportRef = useRef<HTMLDivElement | null>(null);
	const trackRef = useRef<HTMLDivElement | null>(null);

	const [layoutCache, setLayoutCache] = useState<LayoutCache>({ viewportWidth: 0, itemWidthPx: 0, leftOffset: 0 });
	const [originItems, setOriginItems] = useState<React.ReactNode[]>([]);

	const [curRealIndex, setCurRealIndex] = useState<number>(0);
	const [curVirtualIndex, setCurVirtualIndex] = useState<number>(cloneOffset);

	const [isTransitioning, setIsTransitioning] = useState<boolean>(false);

	const autoplayTimer = useRef<number | null>(null);

	const virtualItems = (() => {
		const items = originItems;
		if (items.length <= 1) return items;
		return [...items.slice(-2), ...items, ...items.slice(0, 2)];
	})();

	const itemStyle = useCallback(() => {
		if (typeof itemWidth === "number") {
			const vw = layoutCache.viewportWidth;
			const w = vw ? `${(vw * itemWidth) / 100}px` : `${itemWidth}%`;
			return { width: w } as React.CSSProperties;
		}
		return { width: itemWidth as string } as React.CSSProperties;
	}, [itemWidth, layoutCache.viewportWidth]);

	const arrowStyle = useCallback(() => {
		if (typeof arrowSize === "number") {
			const size = arrowSize;
			return {
				width: `${size}px`,
				height: `${size}px`,
				fontSize: `${Math.round(size * 0.5)}px`,
			} as React.CSSProperties;
		}
		const size = parseFloat(String(arrowSize)) || 45;
		return { width: `${size}px`, height: `${size}px`, fontSize: `${Math.round(size * 0.5)}px` } as React.CSSProperties;
	}, [arrowSize]);

	const trackStyle = useCallback(() => {
		const { viewportWidth, itemWidthPx, leftOffset } = layoutCache;
		if (!viewportWidth || !itemWidthPx) {
			return {
				gap: `${gap}px`,
				transform: `translateX(0px)`,
				transition: isTransitioning ? "transform 0.4s ease-out" : "none",
			} as React.CSSProperties;
		}

		const translate = -(curVirtualIndex * (itemWidthPx + gap) + leftOffset);
		return {
			gap: `${gap}px`,
			transform: `translateX(${translate}px)`,
			transition: isTransitioning ? "transform 0.4s ease-out" : "none",
		} as React.CSSProperties;
	}, [layoutCache, curVirtualIndex, gap, isTransitioning]);

	const realToVirtual = useCallback(
		(realPos: number) => {
			const len = originItems.length || 0;
			if (len === 0) return cloneOffset;
			const normalized = ((realPos % len) + len) % len;
			return normalized + cloneOffset;
		},
		[originItems]
	);

	const virtualToReal = useCallback(
		(virtualPos: number) => {
			const len = originItems.length || 0;
			if (len === 0) return 0;
			return (((virtualPos - cloneOffset) % len) + len) % len;
		},
		[originItems]
	);

	function initLayout() {
		setCurRealIndex(initialIndex || 0);
		setCurVirtualIndex(realToVirtual(initialIndex || 0));
	}

	function measureLayoutCache() {
		if (!viewportRef.current) return;

		const viewportWidth = viewportRef.current.clientWidth || 0;
		let itemWidthPx = 0;

		if (typeof itemWidth === "number") {
			itemWidthPx = (viewportWidth * itemWidth) / 100;
		}

		if (!itemWidthPx) {
			const firstChild = trackRef.current?.children[0] as HTMLElement | undefined;
			itemWidthPx = firstChild?.clientWidth || 0;
		}

		const leftOffset = itemWidthPx / 2 - viewportWidth / 2;
		setLayoutCache({ viewportWidth, itemWidthPx, leftOffset });
	}

	function moveToIndex(targetIndex: number, skipTransition = false) {
		const length = originItems.length;
		if (length === 0) return;

		if (skipTransition) {
			setIsTransitioning(false);
			setCurVirtualIndex((v) => {
				const newV = v + targetIndex;
				setCurRealIndex(virtualToReal(newV));
				return newV;
			});
			return;
		}

		setIsTransitioning(true);
		setCurVirtualIndex((v) => v + targetIndex);
	}

	const handlePrev = () => {
		clearAutoplay();
		moveToIndex(-1);
		setupAutoplay();
	};

	const handleNext = () => {
		clearAutoplay();
		moveToIndex(1);
		setupAutoplay();
	};

	const handleJumpTo = (realIdx: number) => {
		clearAutoplay();
		const virtualIndex = realToVirtual(realIdx);
		setIsTransitioning(true);
		setCurVirtualIndex(virtualIndex);
		setupAutoplay();
	};

	function handleTransitionEnd() {
		const len = originItems.length;
		if (len === 0) return;

		const virtualIndex = curVirtualIndex;
		if (virtualIndex < cloneOffset) {
			const newV = virtualIndex + len;
			moveToIndex(newV - virtualIndex, true);
			return;
		}

		if (virtualIndex >= cloneOffset + len) {
			const newV = virtualIndex - len;
			moveToIndex(newV - virtualIndex, true);
			return;
		}

		setCurRealIndex(virtualToReal(virtualIndex) % originItems.length);
	}

	function setupAutoplay() {
		if (!autoplay || originItems.length <= 1) return;
		clearAutoplay();
		autoplayTimer.current = window.setInterval(() => {
			moveToIndex(1);
		}, interval);
	}

	function clearAutoplay() {
		if (!autoplayTimer.current) return;
		clearInterval(autoplayTimer.current);
		autoplayTimer.current = null;
	}

	const onResize = () => {
		measureLayoutCache();
		setIsTransitioning(false);
	};

	useEffect(() => {
		const items = React.Children.toArray(children || []) as React.ReactNode[];
		setOriginItems(items.map((c) => c));

		const raf = window.requestAnimationFrame(() => {
			initLayout();
			measureLayoutCache();
			setupAutoplay();
		});

		window.addEventListener("resize", onResize);
		return () => {
			clearAutoplay();
			window.removeEventListener("resize", onResize);
			window.cancelAnimationFrame(raf);
		};
	}, [children]);

	useEffect(() => {
		measureLayoutCache();
	}, [curVirtualIndex]);

	return (
		<div style={{ position: "relative", width: "100%", overflow: "hidden" }}>
			{showArrows && originItems.length > 0 && (
				<div style={{ position: "absolute", inset: 0, zIndex: 10, pointerEvents: "none" }}>
					<button
						className="arrow prev"
						style={{
							...(arrowStyle() as React.CSSProperties),
							pointerEvents: "all",
							position: "absolute",
							top: "50%",
							transform: "translateY(-50%)",
							left: 12,
							border: "none",
							borderRadius: "50%",
							background: "rgba(0,0,0,0.25)",
							color: "#fff",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
						}}
						onClick={handlePrev}>
						<svg
							style={{ width: "60%", height: "60%" }}
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth={2}>
							<polyline points="15 18 9 12 15 6" />
						</svg>
					</button>
					<button
						className="arrow next"
						style={{
							...(arrowStyle() as React.CSSProperties),
							pointerEvents: "all",
							position: "absolute",
							top: "50%",
							transform: "translateY(-50%)",
							right: 12,
							border: "none",
							borderRadius: "50%",
							background: "rgba(0,0,0,0.25)",
							color: "#fff",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
						}}
						onClick={handleNext}>
						<svg
							style={{ width: "60%", height: "60%" }}
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth={2}>
							<polyline points="9 18 15 12 9 6" />
						</svg>
					</button>
				</div>
			)}

			<div ref={viewportRef} className="viewport" style={{ width: "100%", overflow: "hidden", position: "relative" }}>
				<div
					ref={trackRef}
					className="track"
					style={{ display: "flex", alignItems: "center", padding: "20px 0", ...(trackStyle() as React.CSSProperties) }}
					onTransitionEnd={handleTransitionEnd}>
					{virtualItems.map((child, idx) => (
						<div key={idx} style={{ ...(itemStyle() as React.CSSProperties), flexShrink: 0 }}>
							{child}
						</div>
					))}
				</div>
			</div>

			{showIndicator && originItems.length > 0 && (
				<div
					className="indicator-bar"
					style={{
						position: "absolute",
						bottom: 35,
						left: "50%",
						transform: "translateX(-50%)",
						display: "flex",
						gap: 8,
						zIndex: 2,
					}}>
					{originItems.map((_, idx) => (
						<span
							key={idx}
							className={`indicator ${idx === curRealIndex ? "active" : ""}`}
							onClick={() => handleJumpTo(idx)}
							style={{
								width: 30,
								height: 4,
								background: idx === curRealIndex ? "#fff" : "rgba(255,255,255,0.45)",
								cursor: "pointer",
								transition: "all 0.25s",
							}}
						/>
					))}
				</div>
			)}
		</div>
	);
};

export default HorizontalTiledCarousel;

// src/components/tiled-carousel/horizontal.vue
<template>
    <div class="carousel-container">
        <div v-if="showArrows && originItems.length > 0" class="arrow-container">
            <button class="arrow prev" :style="arrowStyle" @click="handlePrev">
                <svg style="width:60%;height:60%" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    stroke-width="2">
                    <polyline points="15 18 9 12 15 6"></polyline>
                </svg>
            </button>
            <button class="arrow next" :style="arrowStyle" @click="handleNext">
                <svg style="width:60%;height:60%" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    stroke-width="2">
                    <polyline points="9 18 15 12 9 6"></polyline>
                </svg>
            </button>
        </div>

        <div ref="viewportRef" class="viewport">
            <div ref="trackRef" class="track" :style="trackStyle" @transitionend="handleTransitionEnd">
                <template v-for="(vnode, index) in virtualItems" :key="index">
                    <component :is="vnode" :style="itemStyle" />
                </template>
            </div>
        </div>

        <div v-if="showIndicator && originItems.length > 0" class="indicator-bar">
            <span v-for="(_, idx) in originItems" :key="idx" class="indicator" :class="{ active: idx === curRealIndex }"
                @click="handleJumpTo(idx)" />
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, useSlots, nextTick, watch } from "vue";

type Props = {
    itemWidth?: number | string;
    gap?: number;
    autoplay?: boolean;
    interval?: number;
    showArrows?: boolean;
    showIndicator?: boolean;
    arrowSize?: number;
    initialIndex?: number;
}

const props = withDefaults(defineProps<Props>(), {
    itemWidth: 60,
    gap: 16,
    autoplay: false,
    interval: 3000,
    showArrows: true,
    showIndicator: true,
    arrowSize: 45,
    initialIndex: 0,
});

type LayoutCache = {
    viewportWidth: number;
    itemWidthPx: number;
    leftOffset: number;
}

const layoutCache = ref<LayoutCache>({
    viewportWidth: 0,
    itemWidthPx: 0,
    leftOffset: 0,
});

const slots = useSlots();

const viewportRef = ref<HTMLElement | null>(null);
const trackRef = ref<HTMLElement | null>(null);

const cloneOffset = 2;
const curRealIndex = ref<number>(0);
const curVirtualIndex = ref<number>(0);

const isTransitioning = ref<boolean>(false);
const autoplayTimerId = ref<number | null>(null);

const originItems = ref<any[]>([]);
const virtualItems = computed(() => {
    const items = originItems.value;
    if (items.length <= 1) return items;
    return [...items.slice(-2), ...items, ...items.slice(0, 2)];
});

const itemStyle = computed(() => {
    if (typeof props.itemWidth === "number") {
        const vw = layoutCache.value.viewportWidth;
        const itemWidth = vw ? `${(vw * props.itemWidth) / 100}px` : `${props.itemWidth}%`;
        return { width: itemWidth };
    }

    return { width: props.itemWidth as string };
});
const arrowStyle = computed(() => {
    if (typeof props.arrowSize === "number") {
        const size = props.arrowSize;
        return {
            width: `${size}px`,
            height: `${size}px`,
            fontSize: `${Math.round(size * 0.5)}px`,
        }
    }

    const size = parseFloat(String(props.arrowSize)) || 45;
    return {
        width: `${size}px`,
        height: `${size}px`,
        fontSize: `${Math.round(size * 0.5)}px`,
    }

});
const trackStyle = computed(() => {
    const { viewportWidth, itemWidthPx, leftOffset } = layoutCache.value;

    if (!viewportWidth || !itemWidthPx) {
        return {
            gap: `${props.gap}px`,
            transform: `translateX(0px)`,
            transition: isTransitioning.value ? "transform 0.4s ease-out" : "none",
        };
    }

    const translate = -(curVirtualIndex.value * (itemWidthPx + props.gap) + leftOffset);
    return {
        gap: `${props.gap}px`,
        transform: `translateX(${translate}px)`,
        transition: isTransitioning.value ? "transform 0.4s ease-out" : "none",
    };
});

onMounted(async () => {
    const slotTarget = slots.default ? slots.default() : [];
    originItems.value = (slotTarget[0]?.children || []) as any[];

    nextTick();

    initLayout();
    measureLayoutCache();

    setupAutoplay();
    window.addEventListener("resize", onResize);
});

onUnmounted(() => {
    clearAutoplay();
    window.removeEventListener("resize", onResize);
});

function initLayout() {
    curRealIndex.value = props.initialIndex || 0
    curVirtualIndex.value = realToVirtual(curRealIndex.value);
}

function measureLayoutCache() {
    if (!viewportRef.value) return;

    let viewportWidth = 0;
    let itemWidthPx = 0;
    let leftOffset = 0;

    viewportWidth = viewportRef.value.clientWidth;

    if (typeof props.itemWidth === "number") {
        itemWidthPx = (viewportWidth * props.itemWidth) / 100;
    }
    if (!itemWidthPx) {
        const firstChild = trackRef.value?.children[0] as HTMLElement | undefined;
        itemWidthPx = firstChild?.clientWidth || 0;
    }

    leftOffset = itemWidthPx / 2 - viewportWidth / 2;

    layoutCache.value = { viewportWidth, itemWidthPx, leftOffset };
}


function realToVirtual(realPos: number) {
    const len = originItems.value.length || 0;
    if (len === 0) return cloneOffset;

    const normalized = ((realPos % len) + len) % len;
    return normalized + cloneOffset;
}
function virtualToReal(virtualPos: number) {
    const len = originItems.value.length || 0;
    if (len === 0) return 0;

    return ((virtualPos - cloneOffset) % len + len) % len;
}

function moveToIndex(targetIndex: number, skipTransition = false) {
    const length = originItems.value.length;
    if (length === 0) return;

    //[ >2, 3, 1, 2, 3, 1, 2]
    //[ 1, >2, 3]
    if (skipTransition) {
        isTransitioning.value = false;

        //[ 2, >3, 1, 2, 3, 1, 2]
        curVirtualIndex.value = curVirtualIndex.value + targetIndex;
        //[ 1, 2, >3]
        curRealIndex.value = virtualToReal(curVirtualIndex.value);
        return
    }

    isTransitioning.value = true;
    curVirtualIndex.value = curVirtualIndex.value + targetIndex;
}

const handlePrev = () => {
    clearAutoplay();
    moveToIndex(-1);
    setupAutoplay();
};

const handleNext = () => {
    clearAutoplay();
    moveToIndex(1);
    setupAutoplay();
};

const handleJumpTo = (realIdx: number) => {
    clearAutoplay();
    const virtualIndex = realToVirtual(realIdx);
    isTransitioning.value = true;
    curVirtualIndex.value = virtualIndex;
    setupAutoplay();
};

function handleTransitionEnd() {
    const len = originItems.value.length;
    if (len === 0) return;

    const virtualIndex = curVirtualIndex.value;
    if (virtualIndex < cloneOffset) {
        const newV = virtualIndex + len;
        moveToIndex(newV - virtualIndex, true);
        return
    }

    if (virtualIndex >= cloneOffset + len) {
        const newV = virtualIndex - len;
        moveToIndex(newV - virtualIndex, true);
        return
    }
    curRealIndex.value = virtualToReal(virtualIndex) % originItems.value.length;
}

function setupAutoplay() {
    if (!props.autoplay || originItems.value.length <= 1) return;

    clearAutoplay();
    autoplayTimerId.value = window.setInterval(() => {
        moveToIndex(1);
    }, props.interval);
}
function clearAutoplay() {
    if (!autoplayTimerId.value) return;

    clearInterval(autoplayTimerId.value);
    autoplayTimerId.value = null;
}

function onResize() {
    measureLayoutCache();
    isTransitioning.value = false;
}
</script>

<style scoped>
.carousel-container {
    position: relative;
    width: 100%;
    overflow: hidden;
}

.arrow-container {
    position: absolute;
    inset: 0;
    z-index: 10;
    pointer-events: none;
}

.arrow {
    pointer-events: all;
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    border: none;
    background: rgba(0, 0, 0, 0.25);
    color: #fff;
    cursor: pointer;
}

.arrow.prev {
    left: 12px;
}

.arrow.next {
    right: 12px;
}

.viewport {
    width: 100%;
    overflow: hidden;
    position: relative;
}

.track {
    display: flex;
    align-items: center;
    padding: 20px 0;
}

.track>* {
    flex-shrink: 0;
}

.indicator-bar {
    position: absolute;
    bottom: 35px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    gap: 8px;
    z-index: 2;
}

.indicator {
    width: 30px;
    height: 4px;
    background: rgba(255, 255, 255, 0.45);
    cursor: pointer;
    transition: all 0.25s;
}

.indicator.active {
    background: #fff;
}
</style>
