// src/views/infinite-scroll-list/index.tsx
import SeamlessScroll from "../../components/infinite-scroll-list";

const SeamlessScrollDemo: React.FC = () => {
	const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`);

	return (
		<SeamlessScroll list={items} visibleRows={5}>
			{items.map((item, index) => (
				<div key={index} className="box-row">
					<span>{item}</span>
				</div>
			))}
		</SeamlessScroll>
	);
};
export default SeamlessScrollDemo;

// src/views/infinite-scroll-list/index.vue
<script setup lang="ts">
import InfiniteScrollList from "./../../components/infinite-scroll-list/index.vue"
const items = Array.from({ length: 8 }).map((_, i) => `Item ${i + 1}`)
</script>

<template>
    <InfiniteScrollList :visibleRows="3">
        <div v-for="(item, idx) in items" :key="idx" class="box-row">
            {{ item }}
        </div>
    </InfiniteScrollList>
</template>
