// src/views/showcase-carousel/vertical/vertical-full-demo.tsx
import VerticalShowcaseCarousel from "../../../components/showcase-carousel/vertical.tsx";

const HorizontalSimpleDemo: React.FC = () => {
	const cardData = [
		{ title: "卡片 1", color: "#ff6b6b" },
		{ title: "卡片 2", color: "#4ecdc4" },
		{ title: "卡片 3", color: "#45b7d1" },
		{ title: "卡片 4", color: "#96ceb4" },
		{ title: "卡片 5", color: "#ffeaa7" },
	];

	function onChange(index: number) {
		console.log("当前卡片索引：", index);
	}

	function onCardClick(index: number) {
		const card = cardData[index];
		console.log(`点击了 ${card.title}，索引：${index}`);
	}

	return (
		<div style={{ height: "340px" }}>
			<VerticalShowcaseCarousel
				itemHeight={60}
				gap={15}
				autoplay={true}
				interval={2000}
				showArrows={true}
				indicatorPosition="left"
				change={onChange}
				click={onCardClick}>
				{cardData.map((item) => (
					<div
						style={{
							background: item.color,
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							justifyContent: "center",
							color: "#fff",
							cursor: "pointer",
							transition: "transform 0.3s",
						}}>
						<div>{item.title}</div>
					</div>
				))}
			</VerticalShowcaseCarousel>
		</div>
	);
};

export default HorizontalSimpleDemo;

// src/views/showcase-carousel/vertical/vertical-full-demo.vue
<script setup lang="ts">
import VerticalShowcaseCarousel from '../../../components/showcase-carousel/vertical.vue';

const cardData = [
    { title: "卡片 1", color: "#ff6b6b" },
    { title: "卡片 2", color: "#4ecdc4" },
    { title: "卡片 3", color: "#45b7d1" },
    { title: "卡片 4", color: "#96ceb4" },
    { title: "卡片 5", color: "#ffeaa7" },
];

function onChange(index: number) {
    console.log("当前卡片索引：", index);
}

function onCardClick(index: number) {
    const card = cardData[index];
    console.log(`点击了 ${card.title}，索引：${index}`);
}

</script>

<template>
    <div class="carousel-wrapper">
        <VerticalShowcaseCarousel @click="onCardClick" :itemHeight="60" :gap="15" :autoplay="true"
            indicatorPosition="left" :interval="2000" :showArrows="true" @change="onChange">
            <div v-for="(card, index) in cardData" :key="index" class="carousel-card"
                :style="{ backgroundColor: card.color }">
                <div>{{ card.title }}</div>
            </div>
        </VerticalShowcaseCarousel>
    </div>
</template>

<style scoped>
.carousel-wrapper {
    height: 340px;
}

.carousel-card {
    display: flex;
    justify-content: center;
    align-items: center;
    color: #ffffff;
    cursor: pointer;
}
</style>
