// src/views/showcase-carousel/vertical/vertical-simple-demo.vue
<script setup lang="ts">
import VerticalShowcaseCarousel from '../../../components/showcase-carousel/vertical.vue';

const cardData = [
    { title: "卡片 1", color: "#ff6b6b" },
    { title: "卡片 2", color: "#4ecdc4" },
    { title: "卡片 3", color: "#45b7d1" },
    { title: "卡片 4", color: "#96ceb4" },
    { title: "卡片 5", color: "#ffeaa7" },
];

</script>

<template>
    <div class="carousel-wrapper">
        <VerticalShowcaseCarousel>
            <div v-for="(card, index) in cardData" :key="index" class="carousel-card"
                :style="{ backgroundColor: card.color }">
                <div>{{ card.title }}</div>
            </div>
        </VerticalShowcaseCarousel>
    </div>
</template>

<style scoped>
.carousel-wrapper {
    height: 340px;
}

.carousel-card {
    display: flex;
    justify-content: center;
    align-items: center;
    color: #ffffff;
    cursor: pointer;
}
</style>

// src/views/showcase-carousel/vertical/vertical-simple-demo.tsx
import VerticalShowcaseCarousel from "../../../components/showcase-carousel/vertical.tsx";

const HorizontalSimpleDemo: React.FC = () => {
	const cardData = [
		{ title: "卡片 1", color: "#ff6b6b" },
		{ title: "卡片 2", color: "#4ecdc4" },
		{ title: "卡片 3", color: "#45b7d1" },
		{ title: "卡片 4", color: "#96ceb4" },
		{ title: "卡片 5", color: "#ffeaa7" },
	];

	return (
		<div style={{ height: "340px" }}>
			<VerticalShowcaseCarousel>
				{cardData.map((item) => (
					<div
						style={{
							background: item.color,
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							justifyContent: "center",
							color: "#fff",
							cursor: "pointer",
							transition: "transform 0.3s",
						}}>
						<div>{item.title}</div>
					</div>
				))}
			</VerticalShowcaseCarousel>
		</div>
	);
};

export default HorizontalSimpleDemo;
